import JSZip from 'jszip';
import { saveAs } from 'file-saver';
import type { Batch, EA, BatchSettings } from '@/types';

const generateIniContent = (
  ea: EA,
  symbol: string,
  timeframe: string,
  settings: BatchSettings,
  jobIndex: number
): string => {
  const timeframeMap: Record<string, number> = {
    M1: 1,
    M5: 5,
    M15: 15,
    M30: 30,
    H1: 60,
    H4: 240,
    D1: 1440,
    W1: 10080,
    MN1: 43200,
  };

  const modelValue = settings.modelingMode === 'every_tick' ? 0 : settings.modelingMode === 'ohlc_1min' ? 1 : 2;
  const spreadValue = settings.spreadMode === 'current' ? 0 : settings.fixedSpread || 10;
  const optValue = settings.optimizationMode ? 1 : 0;
  const fromDate = settings.startDate.replace(/-/g, '.');
  const toDate = settings.endDate.replace(/-/g, '.');
  const magicNum = ea.magicNumber || 100000 + jobIndex;

  return `; MT5 Strategy Tester Configuration
; Generated by BatchBacktest Hub
; Job ${jobIndex + 1}: ${ea.name} on ${symbol} ${timeframe}
; Generated at: ${new Date().toISOString()} UTC

[Tester]
Expert=${ea.name}
Symbol=${symbol}
Period=${timeframeMap[timeframe] || 60}
FromDate=${fromDate}
ToDate=${toDate}
Model=${modelValue}
Spread=${spreadValue}
Optimization=${optValue}
Deposit=${settings.initialDeposit}
Currency=USD
Leverage=${settings.leverage}
UseLocal=1
Visual=0
ReplaceReport=1
ShutdownTerminal=1
Report=reports\\\\${ea.name}_${symbol}_${timeframe}_${jobIndex + 1}

[TesterInputs]
; Add EA-specific input parameters here
; MagicNumber=${magicNum}
`;
};

const generatePowerShellScript = (
  jobs: { ea: EA; symbol: string; timeframe: string }[],
  settings: BatchSettings
): string => {
  const timestamp = new Date().toISOString();
  const totalJobs = jobs.length;
  const maxParallel = settings.maxParallelTerminals;
  const delay = settings.delayBetweenLaunches;

  return `# BatchBacktest Hub - MT5 Runner Script
# Generated at: ${timestamp} UTC
# Total Jobs: ${totalJobs}
# Max Parallel Terminals: ${maxParallel}

param(
    [string]$MT5Path = "C:\\Program Files\\MetaTrader 5\\terminal64.exe",
    [int]$MaxWorkers = ${maxParallel},
    [int]$DelaySeconds = ${delay}
)

$ErrorActionPreference = "Stop"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " BatchBacktest Hub - MT5 Runner" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Validate MT5 path
if (-not (Test-Path $MT5Path)) {
    Write-Host "ERROR: MT5 not found at: $MT5Path" -ForegroundColor Red
    Write-Host "Please specify the correct path using -MT5Path parameter" -ForegroundColor Yellow
    exit 1
}

# Get all INI files
$configDir = Join-Path $PSScriptRoot "configs"
$iniFiles = Get-ChildItem -Path $configDir -Filter "*.ini" | Sort-Object Name

Write-Host "Found $($iniFiles.Count) backtest configurations" -ForegroundColor Green
Write-Host "Max parallel terminals: $MaxWorkers" -ForegroundColor Yellow
Write-Host "Delay between launches: $DelaySeconds seconds" -ForegroundColor Yellow
Write-Host ""

# Create results directories
$reportsDir = Join-Path $PSScriptRoot "reports"
$logsDir = Join-Path $PSScriptRoot "logs"
$csvDir = Join-Path $PSScriptRoot "csv"

New-Item -ItemType Directory -Force -Path $reportsDir | Out-Null
New-Item -ItemType Directory -Force -Path $logsDir | Out-Null
New-Item -ItemType Directory -Force -Path $csvDir | Out-Null

# Job tracking
$runningJobs = @()
$completedJobs = 0
$totalJobs = $iniFiles.Count
$startTime = Get-Date

function Start-BacktestJob {
    param([System.IO.FileInfo]$ConfigFile)
    
    $configPath = $ConfigFile.FullName
    $logFile = Join-Path $logsDir "$($ConfigFile.BaseName).log"
    
    Write-Host "Starting: $($ConfigFile.Name)" -ForegroundColor Green
    
    $process = Start-Process -FilePath $MT5Path -ArgumentList "/config:$configPath" -PassThru -WindowStyle Minimized
    
    return @{
        Process = $process
        ConfigFile = $ConfigFile
        StartTime = Get-Date
    }
}

# Main execution loop
$jobIndex = 0
foreach ($ini in $iniFiles) {
    # Wait if we have max workers running
    while ($runningJobs.Count -ge $MaxWorkers) {
        $stillRunning = @()
        foreach ($job in $runningJobs) {
            if ($job.Process.HasExited) {
                $completedJobs++
                $elapsed = (Get-Date) - $job.StartTime
                Write-Host "Completed: $($job.ConfigFile.Name)" -ForegroundColor Cyan
            } else {
                $stillRunning += $job
            }
        }
        $runningJobs = $stillRunning
        if ($runningJobs.Count -ge $MaxWorkers) {
            Start-Sleep -Seconds 5
        }
    }
    
    # Start new job
    $job = Start-BacktestJob -ConfigFile $ini
    $runningJobs += $job
    $jobIndex++
    
    # Progress
    $percentComplete = [math]::Round(($jobIndex / $totalJobs) * 100)
    Write-Progress -Activity "Running Backtests" -Status "$jobIndex of $totalJobs" -PercentComplete $percentComplete
    
    # Delay between launches
    if ($jobIndex -lt $totalJobs) {
        Start-Sleep -Seconds $DelaySeconds
    }
}

# Wait for remaining jobs
Write-Host ""
Write-Host "Waiting for remaining $($runningJobs.Count) jobs to complete..." -ForegroundColor Yellow
while ($runningJobs.Count -gt 0) {
    $stillRunning = @()
    foreach ($job in $runningJobs) {
        if ($job.Process.HasExited) {
            $completedJobs++
            Write-Host "Completed: $($job.ConfigFile.Name)" -ForegroundColor Cyan
        } else {
            $stillRunning += $job
        }
    }
    $runningJobs = $stillRunning
    if ($runningJobs.Count -gt 0) {
        Start-Sleep -Seconds 5
    }
}

# Summary
$totalElapsed = (Get-Date) - $startTime
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Batch Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Total Jobs: $completedJobs" -ForegroundColor White
Write-Host ""
Write-Host "Reports saved to: $reportsDir" -ForegroundColor Yellow
Write-Host ""

Read-Host "Press Enter to exit"
`;
};

const generateBatWrapper = (): string => {
  return `@echo off
REM BatchBacktest Hub - Windows Batch Wrapper
REM This script runs the PowerShell runner with execution policy bypass

echo ========================================
echo  BatchBacktest Hub - MT5 Runner
echo ========================================
echo.

REM Check if PowerShell is available
where powershell >nul 2>nul
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: PowerShell not found!
    pause
    exit /b 1
)

REM Run the PowerShell script
powershell -ExecutionPolicy Bypass -File "%~dp0run_backtests.ps1" %*

pause
`;
};

const generateReadme = (
  batchName: string,
  jobs: { ea: EA; symbol: string; timeframe: string }[],
  settings: BatchSettings
): string => {
  const timestamp = new Date().toISOString();
  const symbolList = settings.symbols.join(', ');
  const tfList = settings.timeframes.join(', ');
  const deposit = settings.initialDeposit.toLocaleString();
  const modelText = settings.modelingMode.replace(/_/g, ' ');
  const spreadText = settings.spreadMode === 'current' ? 'Current spread' : 'Fixed (' + (settings.fixedSpread || 10) + ' points)';
  const optText = settings.optimizationMode ? 'Enabled' : 'Disabled';
  
  const eaList = jobs.map((j, i) => `${i + 1}. **${j.ea.name}** - ${j.symbol} ${j.timeframe}`).join('\n');

  return `# BatchBacktest Hub - Runner Bundle

## Batch: ${batchName}
Generated: ${timestamp} UTC

---

## Quick Start

### Step 1: Extract This Bundle
Extract this ZIP file to a location on your PC (e.g., C:\\Backtests\\${batchName})

### Step 2: Verify MT5 Installation
Ensure MetaTrader 5 is installed. Default path: C:\\Program Files\\MetaTrader 5\\terminal64.exe

### Step 3: Copy EAs to MT5
Copy your Expert Advisors (.ex5 files) to your MT5 data folder:
[MT5 Data Folder]\\MQL5\\Experts\\

To find your data folder: In MT5, go to File > Open Data Folder

### Step 4: Run the Batch
**Option A (Recommended):** Double-click run_backtests.bat

**Option B (Advanced):** Open PowerShell and run:
.\\run_backtests.ps1 -MT5Path "C:\\Path\\To\\terminal64.exe" -MaxWorkers 4

---

## Batch Configuration

| Setting | Value |
|---------|-------|
| Total Jobs | ${jobs.length} |
| Symbols | ${symbolList} |
| Timeframes | ${tfList} |
| Date Range | ${settings.startDate} to ${settings.endDate} |
| Initial Deposit | $${deposit} |
| Leverage | 1:${settings.leverage} |
| Modeling | ${modelText} |
| Spread Mode | ${spreadText} |
| Optimization | ${optText} |
| Max Parallel Terminals | ${settings.maxParallelTerminals} |
| Delay Between Launches | ${settings.delayBetweenLaunches}s |

---

## EAs Included

${eaList}

---

## Folder Structure

${batchName}/
- configs/           # MT5 .ini configuration files
- reports/           # Output: HTML/XML reports (created after run)
- logs/              # Output: Execution logs (created after run)
- csv/               # Output: CSV data exports (created after run)
- run_backtests.ps1  # PowerShell runner script
- run_backtests.bat  # Windows batch wrapper
- README.md          # This file

---

## After Running

1. **Reports** will be saved to the reports/ folder
2. **Import Results**: Go back to BatchBacktest Hub and drag & drop the reports
3. **Analyze**: View your leaderboard and compare EAs

---

## Troubleshooting

### MT5 Not Found
Specify the correct path when running:
.\\run_backtests.ps1 -MT5Path "D:\\MT5\\terminal64.exe"

### PowerShell Execution Policy Error
Run this in an elevated PowerShell:
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

### Tests Not Starting
- Ensure EAs are compiled (.ex5) and in the correct folder
- Check that symbol names match your broker's naming

---

## Support

Generated by BatchBacktest Hub
For issues, check the documentation or contact support.
`;
};

export const generateBundle = async (
  batch: Batch,
  eas: EA[],
  onProgress?: (progress: number) => void
): Promise<void> => {
  const zip = new JSZip();
  const configsFolder = zip.folder('configs');
  const reportsFolder = zip.folder('reports');
  const logsFolder = zip.folder('logs');
  const csvFolder = zip.folder('csv');

  // Generate jobs
  const jobs: { ea: EA; symbol: string; timeframe: string }[] = [];
  for (const eaId of batch.eaIds) {
    const ea = eas.find((e) => e.id === eaId);
    if (!ea) continue;

    for (const symbol of batch.settings.symbols) {
      for (const timeframe of batch.settings.timeframes) {
        jobs.push({ ea, symbol, timeframe });
      }
    }
  }

  // Generate INI files
  jobs.forEach((job, index) => {
    const iniContent = generateIniContent(
      job.ea,
      job.symbol,
      job.timeframe,
      batch.settings,
      index
    );
    const fileName = `${String(index + 1).padStart(4, '0')}_${job.ea.name}_${job.symbol}_${job.timeframe}.ini`;
    configsFolder?.file(fileName, iniContent);
    onProgress?.((index / jobs.length) * 50);
  });

  // Generate scripts
  zip.file('run_backtests.ps1', generatePowerShellScript(jobs, batch.settings));
  zip.file('run_backtests.bat', generateBatWrapper());
  zip.file('README.md', generateReadme(batch.name, jobs, batch.settings));

  // Add placeholder files
  reportsFolder?.file('.gitkeep', '');
  logsFolder?.file('.gitkeep', '');
  csvFolder?.file('.gitkeep', '');

  onProgress?.(75);

  // Generate ZIP
  const content = await zip.generateAsync({ 
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  });

  onProgress?.(100);

  // Download
  const safeName = batch.name.replace(/[^a-zA-Z0-9-_]/g, '_');
  saveAs(content, `${safeName}_bundle.zip`);
};
