/**
 * Professional PDF Tearsheet Generator
 * Creates a multi-page A4 PDF with jsPDF (no html2canvas needed for metrics-only pages)
 */
import { jsPDF } from 'jspdf';
import { format } from 'date-fns';

// ── Types ───────────────────────────────────────────────
export interface TearsheetInput {
  // Core metrics
  netProfit: number;
  grossProfit: number;
  grossLoss: number;
  totalTrades: number;
  winningTrades: number;
  losingTrades: number;
  winRate: number;
  profitFactor: number;
  maxDrawdownPercent: number;
  maxDrawdownAmount: number;
  sharpeRatio: number;
  sortinoRatio?: number;
  calmarRatio?: number;
  cagr: number;
  expectancyR: number;
  avgWin: number;
  avgLoss: number;
  largestWin: number;
  largestLoss: number;
  avgHoldTime: number;
  // Data
  equityCurve: number[];
  drawdownCurve: number[];
  trades: Array<{
    entryTime: number | string;
    exitTime: number | string;
    direction: string;
    pnl: number;
    pnlPercent?: number;
    symbol?: string;
    entryPrice?: number;
    exitPrice?: number;
  }>;
  symbol: string;
  dateRange: string;
  // Meta
  traderName?: string;
  strategyName?: string;
}

// ── Helpers ─────────────────────────────────────────────
const A4_W = 210;
const A4_H = 297;
const MARGIN = 15;
const COL_W = (A4_W - MARGIN * 2) / 2;
const BRAND = { r: 0, g: 180, b: 240 }; // Primary cyan
const DARK = { r: 15, g: 17, b: 23 };
const CARD = { r: 24, g: 24, b: 30 };
const TEXT_W = { r: 240, g: 240, b: 240 };
const TEXT_M = { r: 140, g: 140, b: 140 };
const GREEN = { r: 34, g: 197, b: 94 };
const RED = { r: 239, g: 68, b: 68 };

function setColor(doc: jsPDF, c: { r: number; g: number; b: number }) {
  doc.setTextColor(c.r, c.g, c.b);
}

function drawFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const y = A4_H - 8;
  doc.setFontSize(7);
  setColor(doc, TEXT_M);
  doc.text('Generated by MMCai.app • Confidential', MARGIN, y);
  doc.text(`Page ${pageNum} of ${totalPages}`, A4_W - MARGIN, y, { align: 'right' });
}

function newDarkPage(doc: jsPDF) {
  doc.addPage();
  doc.setFillColor(DARK.r, DARK.g, DARK.b);
  doc.rect(0, 0, A4_W, A4_H, 'F');
}

function sectionTitle(doc: jsPDF, text: string, y: number): number {
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  setColor(doc, BRAND);
  doc.text(text, MARGIN, y);
  y += 2;
  doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, A4_W - MARGIN, y);
  return y + 6;
}

function metricRow(
  doc: jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  isGreen?: boolean,
  isRed?: boolean
) {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  setColor(doc, TEXT_M);
  doc.text(label, x, y);
  
  doc.setFont('helvetica', 'bold');
  if (isGreen) setColor(doc, GREEN);
  else if (isRed) setColor(doc, RED);
  else setColor(doc, TEXT_W);
  doc.text(value, x + COL_W - 5, y, { align: 'right' });
}

function heroMetricBox(
  doc: jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  w: number,
  color?: { r: number; g: number; b: number }
) {
  doc.setFillColor(CARD.r, CARD.g, CARD.b);
  doc.roundedRect(x, y, w, 28, 3, 3, 'F');
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  setColor(doc, TEXT_M);
  doc.text(label.toUpperCase(), x + w / 2, y + 9, { align: 'center' });
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  setColor(doc, color || TEXT_W);
  doc.text(value, x + w / 2, y + 21, { align: 'center' });
}

function drawMiniChart(
  doc: jsPDF,
  data: number[],
  x: number,
  y: number,
  w: number,
  h: number,
  lineColor: { r: number; g: number; b: number }
) {
  if (data.length < 2) return;
  const min = Math.min(...data);
  const max = Math.max(...data);
  const range = max - min || 1;
  
  // Chart area background
  doc.setFillColor(CARD.r, CARD.g, CARD.b);
  doc.roundedRect(x, y, w, h, 2, 2, 'F');
  
  const padX = 5;
  const padY = 5;
  const chartW = w - padX * 2;
  const chartH = h - padY * 2;
  
  doc.setDrawColor(lineColor.r, lineColor.g, lineColor.b);
  doc.setLineWidth(0.4);
  
  const step = chartW / (data.length - 1);
  for (let i = 1; i < data.length; i++) {
    const x1 = x + padX + (i - 1) * step;
    const y1 = y + padY + chartH - ((data[i - 1] - min) / range) * chartH;
    const x2 = x + padX + i * step;
    const y2 = y + padY + chartH - ((data[i] - min) / range) * chartH;
    doc.line(x1, y1, x2, y2);
  }
}

function fmt(n: number, dec = 0): string {
  return n.toLocaleString('en-IN', { maximumFractionDigits: dec, minimumFractionDigits: dec });
}

function fmtCurrency(n: number): string {
  const sign = n >= 0 ? '+' : '';
  return `${sign}₹${fmt(Math.abs(n), 0)}`;
}

// ── Main Export ─────────────────────────────────────────
export async function generateProfessionalTearsheet(input: TearsheetInput): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const totalPages = 5;
  const today = format(new Date(), 'dd MMM yyyy');
  const monthStr = format(new Date(), 'MMMyyy');

  // ─── PAGE 1: Cover ─────────────────────────────────
  doc.setFillColor(DARK.r, DARK.g, DARK.b);
  doc.rect(0, 0, A4_W, A4_H, 'F');
  
  // Logo area
  doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
  doc.roundedRect(MARGIN, 20, 10, 10, 2, 2, 'F');
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255, 255, 255);
  doc.text('MMC', MARGIN + 5, 26.5, { align: 'center' });
  
  doc.setFontSize(10);
  setColor(doc, TEXT_M);
  doc.text('MMCai.app', MARGIN + 14, 27);
  
  // Title
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  setColor(doc, TEXT_W);
  doc.text('Performance', MARGIN, 65);
  doc.text('Tearsheet', MARGIN, 78);
  
  // Divider
  doc.setDrawColor(BRAND.r, BRAND.g, BRAND.b);
  doc.setLineWidth(0.8);
  doc.line(MARGIN, 85, MARGIN + 50, 85);
  
  // Meta
  let metaY = 95;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  setColor(doc, TEXT_M);
  
  if (input.strategyName || input.symbol) {
    doc.text(input.strategyName || input.symbol, MARGIN, metaY);
    metaY += 7;
  }
  doc.text(`Period: ${input.dateRange || 'All Data'}`, MARGIN, metaY);
  metaY += 7;
  doc.text(`Generated: ${today}`, MARGIN, metaY);
  metaY += 7;
  if (input.traderName) {
    doc.text(`Trader: ${input.traderName}`, MARGIN, metaY);
    metaY += 7;
  }
  doc.text(`${input.totalTrades} total trades`, MARGIN, metaY);
  
  // Hero metrics
  const boxW = (A4_W - MARGIN * 2 - 12) / 4;
  const boxY = 140;
  const heroMetrics = [
    { label: 'Net P&L', value: fmtCurrency(input.netProfit), color: input.netProfit >= 0 ? GREEN : RED },
    { label: 'Win Rate', value: `${input.winRate.toFixed(1)}%`, color: BRAND },
    { label: 'Profit Factor', value: input.profitFactor.toFixed(2), color: BRAND },
    { label: 'Max Drawdown', value: `-${input.maxDrawdownPercent.toFixed(1)}%`, color: RED },
  ];
  
  heroMetrics.forEach((m, i) => {
    heroMetricBox(doc, m.label, m.value, MARGIN + i * (boxW + 4), boxY, boxW, m.color);
  });
  
  drawFooter(doc, 1, totalPages);

  // ─── PAGE 2: Charts ────────────────────────────────
  newDarkPage(doc);
  let y = 20;
  
  y = sectionTitle(doc, 'Equity Curve', y);
  drawMiniChart(doc, input.equityCurve, MARGIN, y, A4_W - MARGIN * 2, 70, GREEN);
  y += 78;
  
  y = sectionTitle(doc, 'Drawdown', y);
  const ddData = input.drawdownCurve.length > 0 ? input.drawdownCurve : 
    input.equityCurve.map((v, i, arr) => {
      const peak = Math.max(...arr.slice(0, i + 1));
      return peak > 0 ? -((peak - v) / peak) * 100 : 0;
    });
  drawMiniChart(doc, ddData, MARGIN, y, A4_W - MARGIN * 2, 60, RED);
  y += 68;
  
  // Monthly P&L bar representation
  y = sectionTitle(doc, 'Monthly P&L', y);
  const monthlyPnl = computeMonthlyPnl(input.trades);
  const months = Object.entries(monthlyPnl).slice(-12);
  if (months.length > 0) {
    const maxAbs = Math.max(...months.map(([, v]) => Math.abs(v)), 1);
    const barH = 6;
    const barAreaW = A4_W - MARGIN * 2 - 30;
    
    months.forEach(([month, pnl], i) => {
      const rowY = y + i * (barH + 2);
      doc.setFontSize(7);
      setColor(doc, TEXT_M);
      doc.text(month, MARGIN, rowY + 4);
      
      const barW = (Math.abs(pnl) / maxAbs) * (barAreaW / 2);
      const centerX = MARGIN + 30 + barAreaW / 2;
      
      if (pnl >= 0) {
        doc.setFillColor(GREEN.r, GREEN.g, GREEN.b);
        doc.rect(centerX, rowY, barW, barH, 'F');
      } else {
        doc.setFillColor(RED.r, RED.g, RED.b);
        doc.rect(centerX - barW, rowY, barW, barH, 'F');
      }
      
      doc.setFontSize(6);
      setColor(doc, TEXT_W);
      const valX = pnl >= 0 ? centerX + barW + 2 : centerX - barW - 2;
      doc.text(fmtCurrency(pnl), valX, rowY + 4, { align: pnl >= 0 ? 'left' : 'right' });
    });
  }
  
  drawFooter(doc, 2, totalPages);

  // ─── PAGE 3: Detailed Metrics ──────────────────────
  newDarkPage(doc);
  y = 20;
  y = sectionTitle(doc, 'Detailed Performance Metrics', y);
  
  const leftX = MARGIN;
  const rightX = MARGIN + COL_W + 5;
  const rowH = 7.5;
  
  // Left column
  const leftMetrics = [
    ['Total Trades', fmt(input.totalTrades)],
    ['Winning Trades', fmt(input.winningTrades), true],
    ['Losing Trades', fmt(input.losingTrades), false, true],
    ['Win Rate', `${input.winRate.toFixed(1)}%`],
    ['Avg Win', fmtCurrency(input.avgWin), true],
    ['Avg Loss', fmtCurrency(-Math.abs(input.avgLoss)), false, true],
    ['Largest Win', fmtCurrency(input.largestWin), true],
    ['Largest Loss', fmtCurrency(input.largestLoss), false, true],
    ['Profit Factor', input.profitFactor.toFixed(2)],
    ['Expected Value', `${input.expectancyR.toFixed(2)}R`],
  ];
  
  leftMetrics.forEach(([label, value, isG, isR], i) => {
    metricRow(doc, label as string, value as string, leftX, y + i * rowH, isG as boolean, isR as boolean);
  });
  
  // Right column
  const rightMetrics = [
    ['Net Profit', fmtCurrency(input.netProfit), input.netProfit >= 0, input.netProfit < 0],
    ['Gross Profit', fmtCurrency(input.grossProfit), true],
    ['Gross Loss', fmtCurrency(input.grossLoss), false, true],
    ['Max Drawdown', `-${input.maxDrawdownPercent.toFixed(1)}%`, false, true],
    ['Max DD Amount', fmtCurrency(-Math.abs(input.maxDrawdownAmount)), false, true],
    ['Sharpe Ratio', input.sharpeRatio.toFixed(2)],
    ['Sortino Ratio', (input.sortinoRatio ?? 0).toFixed(2)],
    ['Calmar Ratio', (input.calmarRatio ?? 0).toFixed(2)],
    ['CAGR', `${input.cagr.toFixed(1)}%`],
    ['Recovery Factor', input.maxDrawdownAmount !== 0 ? (input.netProfit / Math.abs(input.maxDrawdownAmount)).toFixed(2) : '—'],
  ];
  
  rightMetrics.forEach(([label, value, isG, isR], i) => {
    metricRow(doc, label as string, value as string, rightX, y + i * rowH, isG as boolean, isR as boolean);
  });
  
  drawFooter(doc, 3, totalPages);

  // ─── PAGE 4: Trade Analysis ────────────────────────
  newDarkPage(doc);
  y = 20;
  y = sectionTitle(doc, 'Trade Analysis', y);
  
  const analysis = computeTradeAnalysis(input.trades);
  
  const analysisRows = [
    ['Best Month', analysis.bestMonth.label, fmtCurrency(analysis.bestMonth.value), true],
    ['Worst Month', analysis.worstMonth.label, fmtCurrency(analysis.worstMonth.value), false, true],
    ['Best Day of Week', analysis.bestDay.label, `${analysis.bestDay.value.toFixed(1)}% WR`],
    ['Worst Day of Week', analysis.worstDay.label, `${analysis.worstDay.value.toFixed(1)}% WR`],
    ['Longest Win Streak', `${analysis.longestWinStreak} trades`, '', true],
    ['Longest Loss Streak', `${analysis.longestLossStreak} trades`, '', false, true],
  ];
  
  analysisRows.forEach(([label, value, extra, isG, isR], i) => {
    const rowY = y + i * 9;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    setColor(doc, TEXT_M);
    doc.text(label as string, leftX, rowY);
    
    doc.setFont('helvetica', 'bold');
    if (isG) setColor(doc, GREEN);
    else if (isR) setColor(doc, RED);
    else setColor(doc, TEXT_W);
    doc.text(value as string, leftX + 70, rowY);
    
    if (extra) {
      doc.setFontSize(8);
      setColor(doc, TEXT_M);
      doc.text(extra as string, leftX + 120, rowY);
    }
  });
  
  y += analysisRows.length * 9 + 10;
  
  // Top setups
  if (analysis.topSetups.length > 0) {
    y = sectionTitle(doc, 'Top Winning Setups', y);
    analysis.topSetups.slice(0, 5).forEach(([setup, wr, count], i) => {
      doc.setFontSize(8);
      setColor(doc, TEXT_W);
      doc.text(`${i + 1}. ${setup}`, leftX, y + i * 6);
      setColor(doc, GREEN);
      doc.text(`${(wr as number).toFixed(0)}% WR (${count} trades)`, leftX + 80, y + i * 6);
    });
    y += analysis.topSetups.length * 6 + 10;
  }
  
  if (analysis.worstSetups.length > 0) {
    y = sectionTitle(doc, 'Weakest Setups', y);
    analysis.worstSetups.slice(0, 5).forEach(([setup, wr, count], i) => {
      doc.setFontSize(8);
      setColor(doc, TEXT_W);
      doc.text(`${i + 1}. ${setup}`, leftX, y + i * 6);
      setColor(doc, RED);
      doc.text(`${(wr as number).toFixed(0)}% WR (${count} trades)`, leftX + 80, y + i * 6);
    });
  }
  
  drawFooter(doc, 4, totalPages);

  // ─── PAGE 5: Risk Analysis ─────────────────────────
  newDarkPage(doc);
  y = 20;
  y = sectionTitle(doc, 'Risk Analysis', y);
  
  const riskMetrics = computeRiskMetrics(input);
  
  const riskRows = [
    ['VaR 95% (Daily)', riskMetrics.var95 !== null ? `${riskMetrics.var95.toFixed(2)}%` : 'Insufficient data'],
    ['VaR 99% (Daily)', riskMetrics.var99 !== null ? `${riskMetrics.var99.toFixed(2)}%` : 'Insufficient data'],
    ['Expected Shortfall 95%', riskMetrics.es95 !== null ? `${riskMetrics.es95.toFixed(2)}%` : 'Insufficient data'],
    ['Max Drawdown', `-${input.maxDrawdownPercent.toFixed(1)}%`],
    ['Sharpe Ratio', input.sharpeRatio.toFixed(2)],
    ['Sortino Ratio', (input.sortinoRatio ?? 0).toFixed(2)],
    ['Calmar Ratio', (input.calmarRatio ?? 0).toFixed(2)],
    ['Recovery Factor', input.maxDrawdownAmount !== 0 ? (input.netProfit / Math.abs(input.maxDrawdownAmount)).toFixed(2) : '—'],
  ];
  
  riskRows.forEach(([label, value], i) => {
    metricRow(doc, label, value, leftX, y + i * rowH);
  });
  
  y += riskRows.length * rowH + 12;
  
  // Risk assessment
  y = sectionTitle(doc, 'Risk Assessment', y);
  const assessment = getRiskAssessment(input);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  assessment.forEach((line, i) => {
    setColor(doc, line.color === 'green' ? GREEN : line.color === 'red' ? RED : TEXT_M);
    doc.text(`${line.icon}  ${line.text}`, leftX, y + i * 7);
  });
  
  drawFooter(doc, 5, totalPages);

  // ─── Save ──────────────────────────────────────────
  doc.save(`MMCai_Tearsheet_${monthStr}.pdf`);
}

// ── Analytics helpers ───────────────────────────────────
function computeMonthlyPnl(trades: TearsheetInput['trades']): Record<string, number> {
  const monthly: Record<string, number> = {};
  for (const t of trades) {
    const d = new Date(t.exitTime || t.entryTime);
    const key = format(d, 'MMM yyyy');
    monthly[key] = (monthly[key] || 0) + t.pnl;
  }
  return monthly;
}

function computeTradeAnalysis(trades: TearsheetInput['trades']) {
  // Monthly
  const monthly = computeMonthlyPnl(trades);
  const monthEntries = Object.entries(monthly);
  const bestMonth = monthEntries.reduce((best, [k, v]) => v > best.value ? { label: k, value: v } : best, { label: '—', value: -Infinity });
  const worstMonth = monthEntries.reduce((worst, [k, v]) => v < worst.value ? { label: k, value: v } : worst, { label: '—', value: Infinity });
  
  // Day of week
  const dayStats: Record<number, { wins: number; total: number }> = {};
  const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  for (const t of trades) {
    const d = new Date(t.entryTime).getDay();
    if (!dayStats[d]) dayStats[d] = { wins: 0, total: 0 };
    dayStats[d].total++;
    if (t.pnl > 0) dayStats[d].wins++;
  }
  const dayEntries = Object.entries(dayStats).map(([d, s]) => ({ day: days[+d], wr: s.total > 0 ? (s.wins / s.total) * 100 : 0 }));
  const bestDay = dayEntries.reduce((b, d) => d.wr > b.value ? { label: d.day, value: d.wr } : b, { label: '—', value: 0 });
  const worstDay = dayEntries.reduce((w, d) => d.wr < w.value ? { label: d.day, value: d.wr } : w, { label: '—', value: 100 });
  
  // Streaks
  let winStreak = 0, lossStreak = 0, maxWin = 0, maxLoss = 0;
  for (const t of trades) {
    if (t.pnl > 0) { winStreak++; lossStreak = 0; maxWin = Math.max(maxWin, winStreak); }
    else { lossStreak++; winStreak = 0; maxLoss = Math.max(maxLoss, lossStreak); }
  }
  
  // Setup analysis
  const setupStats: Record<string, { wins: number; total: number }> = {};
  for (const t of trades) {
    const setup = (t as any).setup_type || (t as any).setupType || t.direction;
    if (!setupStats[setup]) setupStats[setup] = { wins: 0, total: 0 };
    setupStats[setup].total++;
    if (t.pnl > 0) setupStats[setup].wins++;
  }
  const setups = Object.entries(setupStats)
    .filter(([, s]) => s.total >= 3)
    .map(([name, s]) => [name, (s.wins / s.total) * 100, s.total] as [string, number, number])
    .sort((a, b) => b[1] - a[1]);
  
  return {
    bestMonth: bestMonth.value === -Infinity ? { label: '—', value: 0 } : bestMonth,
    worstMonth: worstMonth.value === Infinity ? { label: '—', value: 0 } : worstMonth,
    bestDay,
    worstDay,
    longestWinStreak: maxWin,
    longestLossStreak: maxLoss,
    topSetups: setups.slice(0, 5),
    worstSetups: setups.slice(-3).reverse(),
  };
}

function computeRiskMetrics(input: TearsheetInput) {
  // Daily returns from equity curve
  const returns: number[] = [];
  for (let i = 1; i < input.equityCurve.length; i++) {
    const prev = input.equityCurve[i - 1];
    if (prev > 0) returns.push(((input.equityCurve[i] - prev) / prev) * 100);
  }
  
  if (returns.length < 10) return { var95: null, var99: null, es95: null };
  
  const sorted = [...returns].sort((a, b) => a - b);
  const n = sorted.length;
  const var95 = Math.abs(sorted[Math.floor(n * 0.05)]);
  const var99 = Math.abs(sorted[Math.floor(n * 0.01)]);
  const worst5 = sorted.slice(0, Math.max(1, Math.floor(n * 0.05)));
  const es95 = Math.abs(worst5.reduce((s, v) => s + v, 0) / worst5.length);
  
  return { var95, var99, es95 };
}

function getRiskAssessment(input: TearsheetInput): Array<{ icon: string; text: string; color: 'green' | 'red' | 'neutral' }> {
  const items: Array<{ icon: string; text: string; color: 'green' | 'red' | 'neutral' }> = [];
  
  if (input.profitFactor > 1.5) items.push({ icon: '✓', text: 'Profit factor above 1.5 — strong edge', color: 'green' });
  else if (input.profitFactor < 1.0) items.push({ icon: '✗', text: 'Profit factor below 1.0 — unprofitable', color: 'red' });
  else items.push({ icon: '●', text: `Profit factor ${input.profitFactor.toFixed(2)} — marginal edge`, color: 'neutral' });
  
  if (input.maxDrawdownPercent < 15) items.push({ icon: '✓', text: 'Max drawdown under 15% — good risk control', color: 'green' });
  else if (input.maxDrawdownPercent > 30) items.push({ icon: '✗', text: 'Max drawdown over 30% — high risk', color: 'red' });
  else items.push({ icon: '●', text: `Max drawdown ${input.maxDrawdownPercent.toFixed(1)}% — moderate`, color: 'neutral' });
  
  if (input.sharpeRatio > 1.5) items.push({ icon: '✓', text: 'Sharpe above 1.5 — excellent risk-adjusted returns', color: 'green' });
  else if (input.sharpeRatio < 0.5) items.push({ icon: '✗', text: 'Sharpe below 0.5 — poor risk-adjusted returns', color: 'red' });
  else items.push({ icon: '●', text: `Sharpe ${input.sharpeRatio.toFixed(2)} — acceptable`, color: 'neutral' });
  
  if (input.winRate > 55) items.push({ icon: '✓', text: `Win rate ${input.winRate.toFixed(0)}% — positive expectancy`, color: 'green' });
  else if (input.winRate < 40) items.push({ icon: '✗', text: `Win rate ${input.winRate.toFixed(0)}% — needs higher R:R`, color: 'red' });
  
  return items;
}
