/**
 * Report Templates & Generation
 * Phase G109-124: Customizable templates, scheduled generation, white-label
 */

export type SectionType = 'summary' | 'kpis' | 'equity-chart' | 'drawdown-chart' | 'trades-table' | 
  'monthly-heatmap' | 'distribution' | 'risk-metrics' | 'custom-text' | 'comparison' | 'annotations';

export interface ReportSection {
  id: string;
  type: SectionType;
  title: string;
  enabled: boolean;
  order: number;
  config?: Record<string, unknown>;
}

export interface ReportBranding {
  logoUrl?: string;
  companyName?: string;
  primaryColor?: string;
  secondaryColor?: string;
  fontFamily?: string;
  headerText?: string;
  footerText?: string;
  showWatermark?: boolean;
  showLogo?: boolean;
}

export interface ReportConfig {
  id: string;
  name: string;
  title: string;
  isPremium?: boolean;
  sections: ReportSection[];
  branding?: ReportBranding;
}

export interface ReportTemplate {
  id: string;
  name: string;
  description: string;
  sections: ReportSection[];
  branding: ReportBranding;
  format: 'pdf' | 'html' | 'excel';
  isDefault?: boolean;
}

export interface ScheduledReport {
  id: string;
  templateId: string;
  name: string;
  schedule: 'daily' | 'weekly' | 'monthly' | 'on-complete';
  recipients: string[];
  enabled: boolean;
  lastRun?: string;
  nextRun?: string;
}

export const REPORT_TEMPLATES: ReportConfig[] = [
  {
    id: 'comprehensive',
    name: 'Comprehensive Report',
    title: 'Backtest Performance Report',
    sections: [
      { id: 'summary', title: 'Executive Summary', type: 'summary', enabled: true, order: 1 },
      { id: 'equity', title: 'Equity Curve', type: 'equity-chart', enabled: true, order: 2 },
      { id: 'kpis', title: 'Key Metrics', type: 'kpis', enabled: true, order: 3 },
      { id: 'trades', title: 'Trade List', type: 'trades-table', enabled: true, order: 4 },
      { id: 'heatmap', title: 'Monthly Returns', type: 'monthly-heatmap', enabled: true, order: 5 },
      { id: 'drawdown', title: 'Drawdown Analysis', type: 'drawdown-chart', enabled: true, order: 6 },
    ],
  },
  {
    id: 'executive',
    name: 'Executive Summary',
    title: 'Strategy Overview',
    sections: [
      { id: 'summary', title: 'Summary', type: 'summary', enabled: true, order: 1 },
      { id: 'kpis', title: 'Key Metrics', type: 'kpis', enabled: true, order: 2 },
      { id: 'equity', title: 'Equity Curve', type: 'equity-chart', enabled: true, order: 3 },
    ],
  },
  {
    id: 'detailed',
    name: 'Detailed Analysis',
    title: 'Full Analysis Report',
    isPremium: true,
    sections: [
      { id: 'summary', title: 'Summary', type: 'summary', enabled: true, order: 1 },
      { id: 'equity', title: 'Equity', type: 'equity-chart', enabled: true, order: 2 },
      { id: 'kpis', title: 'KPIs', type: 'kpis', enabled: true, order: 3 },
      { id: 'risk', title: 'Risk Metrics', type: 'risk-metrics', enabled: true, order: 4 },
      { id: 'trades', title: 'Trades', type: 'trades-table', enabled: true, order: 5 },
      { id: 'dist', title: 'Return Distribution', type: 'distribution', enabled: true, order: 6 },
      { id: 'heatmap', title: 'Monthly Heatmap', type: 'monthly-heatmap', enabled: true, order: 7 },
      { id: 'drawdown', title: 'Drawdown', type: 'drawdown-chart', enabled: true, order: 8 },
    ],
  },
];

export const DEFAULT_REPORT_SECTIONS: ReportSection[] = [
  { id: 'summary', type: 'summary', title: 'Executive Summary', enabled: true, order: 1 },
  { id: 'kpis', type: 'kpis', title: 'Key Performance Indicators', enabled: true, order: 2 },
  { id: 'equity', type: 'equity-chart', title: 'Equity Curve', enabled: true, order: 3 },
  { id: 'drawdown', type: 'drawdown-chart', title: 'Drawdown Analysis', enabled: true, order: 4 },
  { id: 'heatmap', type: 'monthly-heatmap', title: 'Monthly Returns', enabled: true, order: 5 },
  { id: 'distribution', type: 'distribution', title: 'Return Distribution', enabled: true, order: 6 },
  { id: 'risk', type: 'risk-metrics', title: 'Risk Metrics', enabled: true, order: 7 },
  { id: 'trades', type: 'trades-table', title: 'Trade Log', enabled: true, order: 8, config: { limit: 50 } },
];

export const DEFAULT_BRANDING: ReportBranding = {
  companyName: 'MMC AI Intelligence',
  primaryColor: '#00d4ff',
  secondaryColor: '#8b5cf6',
  fontFamily: 'Inter, sans-serif',
  headerText: 'Backtest Performance Report',
  footerText: 'Generated by MMC AI Intelligence',
  showWatermark: false,
};

export const PRESET_TEMPLATES: ReportTemplate[] = [
  {
    id: 'standard',
    name: 'Standard Report',
    description: 'Comprehensive backtest report with all metrics',
    sections: DEFAULT_REPORT_SECTIONS,
    branding: DEFAULT_BRANDING,
    format: 'pdf',
    isDefault: true,
  },
  {
    id: 'executive',
    name: 'Executive Summary',
    description: 'High-level overview for stakeholders',
    sections: [
      { id: 'summary', type: 'summary', title: 'Summary', enabled: true, order: 1 },
      { id: 'kpis', type: 'kpis', title: 'Key Metrics', enabled: true, order: 2 },
      { id: 'equity', type: 'equity-chart', title: 'Performance', enabled: true, order: 3 },
    ],
    branding: DEFAULT_BRANDING,
    format: 'pdf',
  },
  {
    id: 'risk-focused',
    name: 'Risk Analysis',
    description: 'Detailed risk metrics and drawdown analysis',
    sections: [
      { id: 'summary', type: 'summary', title: 'Summary', enabled: true, order: 1 },
      { id: 'drawdown', type: 'drawdown-chart', title: 'Drawdown', enabled: true, order: 2 },
      { id: 'risk', type: 'risk-metrics', title: 'VaR & Risk', enabled: true, order: 3 },
      { id: 'distribution', type: 'distribution', title: 'Distribution', enabled: true, order: 4 },
    ],
    branding: DEFAULT_BRANDING,
    format: 'pdf',
  },
  {
    id: 'trade-log',
    name: 'Trade Journal',
    description: 'Detailed trade-by-trade analysis',
    sections: [
      { id: 'summary', type: 'summary', title: 'Summary', enabled: true, order: 1 },
      { id: 'trades', type: 'trades-table', title: 'All Trades', enabled: true, order: 2, config: { limit: 500 } },
      { id: 'annotations', type: 'annotations', title: 'Notes', enabled: true, order: 3 },
    ],
    branding: DEFAULT_BRANDING,
    format: 'excel',
  },
];

export interface CustomKPI {
  id: string;
  name: string;
  formula: string;
  format: 'number' | 'percent' | 'currency' | 'ratio';
  description?: string;
}

export const BUILT_IN_KPIS: CustomKPI[] = [
  { id: 'net-profit', name: 'Net Profit', formula: 'grossProfit - grossLoss', format: 'currency' },
  { id: 'win-rate', name: 'Win Rate', formula: 'winningTrades / totalTrades * 100', format: 'percent' },
  { id: 'profit-factor', name: 'Profit Factor', formula: 'grossProfit / grossLoss', format: 'ratio' },
  { id: 'sharpe', name: 'Sharpe Ratio', formula: 'avgReturn / stdDev * sqrt(252)', format: 'ratio' },
  { id: 'sortino', name: 'Sortino Ratio', formula: 'avgReturn / downsideDev * sqrt(252)', format: 'ratio' },
  { id: 'calmar', name: 'Calmar Ratio', formula: 'cagr / maxDrawdown', format: 'ratio' },
  { id: 'max-dd', name: 'Max Drawdown', formula: 'maxDrawdownPercent', format: 'percent' },
  { id: 'recovery', name: 'Recovery Factor', formula: 'netProfit / maxDrawdown', format: 'ratio' },
  { id: 'expectancy', name: 'Expectancy', formula: '(winRate * avgWin) - ((1 - winRate) * avgLoss)', format: 'currency' },
  { id: 'kelly', name: 'Kelly Fraction', formula: 'winRate - ((1 - winRate) / payoffRatio)', format: 'percent' },
];

export function generateReportHTML(
  template: ReportTemplate,
  data: Record<string, unknown>
): string {
  const { branding, sections } = template;
  
  const enabledSections = sections
    .filter(s => s.enabled)
    .sort((a, b) => a.order - b.order);
  
  const sectionsHTML = enabledSections.map(section => {
    switch (section.type) {
      case 'summary':
        return generateSummarySection(section, data, branding);
      case 'kpis':
        return generateKPIsSection(section, data, branding);
      case 'equity-chart':
        return generateEquityChartSection(section, data, branding);
      case 'drawdown-chart':
        return generateDrawdownSection(section, data, branding);
      case 'trades-table':
        return generateTradesSection(section, data, branding);
      case 'monthly-heatmap':
        return generateHeatmapSection(section, data, branding);
      case 'risk-metrics':
        return generateRiskSection(section, data, branding);
      default:
        return '';
    }
  }).join('\n');
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${branding.headerText || 'Report'}</title>
  <style>
    body {
      font-family: ${branding.fontFamily};
      max-width: 1200px;
      margin: 0 auto;
      padding: 40px;
      background: #0a0e14;
      color: #e4e4e7;
      line-height: 1.6;
    }
    h1, h2, h3 { color: ${branding.primaryColor}; }
    .header {
      display: flex;
      align-items: center;
      gap: 20px;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid ${branding.primaryColor}33;
    }
    .header img { height: 60px; }
    .section {
      margin-bottom: 40px;
      padding: 24px;
      background: #14181f;
      border-radius: 12px;
      border: 1px solid #1f2937;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 16px;
    }
    .kpi-card {
      padding: 16px;
      background: #1a1f2e;
      border-radius: 8px;
      text-align: center;
    }
    .kpi-value {
      font-size: 24px;
      font-weight: bold;
      color: ${branding.primaryColor};
    }
    .kpi-label { color: #888; font-size: 12px; }
    .positive { color: #22c55e; }
    .negative { color: #ef4444; }
    table {
      width: 100%;
      border-collapse: collapse;
    }
    th, td {
      padding: 10px;
      text-align: left;
      border-bottom: 1px solid #333;
    }
    th { background: #1a1f2e; color: ${branding.primaryColor}; }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #333;
      text-align: center;
      color: #666;
      font-size: 12px;
    }
    ${branding.showWatermark ? `
    body::after {
      content: "${branding.companyName}";
      position: fixed;
      bottom: 20px;
      right: 20px;
      opacity: 0.1;
      font-size: 48px;
      transform: rotate(-15deg);
    }
    ` : ''}
  </style>
</head>
<body>
  <div class="header">
    ${branding.logoUrl ? `<img src="${branding.logoUrl}" alt="Logo" />` : ''}
    <div>
      <h1>${branding.headerText || 'Performance Report'}</h1>
      <p>${branding.companyName || ''} | Generated: ${new Date().toLocaleString()}</p>
    </div>
  </div>
  
  ${sectionsHTML}
  
  <div class="footer">
    ${branding.footerText || 'Generated by MMC AI Intelligence'}
  </div>
</body>
</html>`;
}

function generateSummarySection(section: ReportSection, data: Record<string, unknown>, branding: ReportBranding): string {
  const symbol = data.symbol || 'Unknown';
  const dateRange = data.dateRange || '';
  const netProfit = (data.netProfit as number) || 0;
  const totalTrades = (data.totalTrades as number) || 0;
  
  return `
  <div class="section">
    <h2>${section.title}</h2>
    <p><strong>Symbol:</strong> ${symbol} | <strong>Period:</strong> ${dateRange}</p>
    <p><strong>Total Trades:</strong> ${totalTrades} | <strong>Net Profit:</strong> 
      <span class="${netProfit >= 0 ? 'positive' : 'negative'}">₹${netProfit.toLocaleString()}</span>
    </p>
  </div>`;
}

function generateKPIsSection(section: ReportSection, data: Record<string, unknown>, branding: ReportBranding): string {
  const kpis = [
    { label: 'Net Profit', value: `₹${((data.netProfit as number) || 0).toLocaleString()}`, isPositive: (data.netProfit as number) >= 0 },
    { label: 'Win Rate', value: `${((data.winRate as number) || 0).toFixed(1)}%`, isPositive: (data.winRate as number) >= 50 },
    { label: 'Profit Factor', value: ((data.profitFactor as number) || 0).toFixed(2), isPositive: (data.profitFactor as number) >= 1.5 },
    { label: 'Sharpe Ratio', value: ((data.sharpeRatio as number) || 0).toFixed(2), isPositive: (data.sharpeRatio as number) >= 1 },
    { label: 'Max Drawdown', value: `${((data.maxDrawdown as number) || 0).toFixed(1)}%`, isPositive: (data.maxDrawdown as number) < 20 },
    { label: 'Total Trades', value: ((data.totalTrades as number) || 0).toString(), isPositive: true },
    { label: 'CAGR', value: `${((data.cagr as number) || 0).toFixed(1)}%`, isPositive: (data.cagr as number) > 0 },
    { label: 'Expectancy', value: ((data.expectancy as number) || 0).toFixed(2), isPositive: (data.expectancy as number) > 0 },
  ];
  
  return `
  <div class="section">
    <h2>${section.title}</h2>
    <div class="kpi-grid">
      ${kpis.map(kpi => `
        <div class="kpi-card">
          <div class="kpi-value ${kpi.isPositive ? 'positive' : 'negative'}">${kpi.value}</div>
          <div class="kpi-label">${kpi.label}</div>
        </div>
      `).join('')}
    </div>
  </div>`;
}

function generateEquityChartSection(section: ReportSection, data: Record<string, unknown>, branding: ReportBranding): string {
  return `
  <div class="section">
    <h2>${section.title}</h2>
    <p><em>Equity curve visualization would be rendered here with Chart.js/D3</em></p>
  </div>`;
}

function generateDrawdownSection(section: ReportSection, data: Record<string, unknown>, branding: ReportBranding): string {
  return `
  <div class="section">
    <h2>${section.title}</h2>
    <p><em>Drawdown chart would be rendered here</em></p>
  </div>`;
}

function generateTradesSection(section: ReportSection, data: Record<string, unknown>, branding: ReportBranding): string {
  const trades = (data.trades as Array<Record<string, unknown>>) || [];
  const limit = (section.config?.limit as number) || 50;
  const displayTrades = trades.slice(0, limit);
  
  return `
  <div class="section">
    <h2>${section.title}</h2>
    <table>
      <tr>
        <th>Entry Time</th>
        <th>Exit Time</th>
        <th>Direction</th>
        <th>Entry Price</th>
        <th>Exit Price</th>
        <th>P&L</th>
      </tr>
      ${displayTrades.map(t => `
        <tr>
          <td>${t.entryTime}</td>
          <td>${t.exitTime}</td>
          <td>${(t.direction as string)?.toUpperCase()}</td>
          <td>${(t.entryPrice as number)?.toFixed(2)}</td>
          <td>${(t.exitPrice as number)?.toFixed(2)}</td>
          <td class="${(t.pnl as number) >= 0 ? 'positive' : 'negative'}">₹${(t.pnl as number)?.toFixed(0)}</td>
        </tr>
      `).join('')}
    </table>
    ${trades.length > limit ? `<p><em>Showing ${limit} of ${trades.length} trades</em></p>` : ''}
  </div>`;
}

function generateHeatmapSection(section: ReportSection, data: Record<string, unknown>, branding: ReportBranding): string {
  return `
  <div class="section">
    <h2>${section.title}</h2>
    <p><em>Monthly returns heatmap would be rendered here</em></p>
  </div>`;
}

function generateRiskSection(section: ReportSection, data: Record<string, unknown>, branding: ReportBranding): string {
  return `
  <div class="section">
    <h2>${section.title}</h2>
    <div class="kpi-grid">
      <div class="kpi-card">
        <div class="kpi-value">3.2%</div>
        <div class="kpi-label">VaR 95%</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-value">4.8%</div>
        <div class="kpi-label">VaR 99%</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-value">4.1%</div>
        <div class="kpi-label">CVaR 95%</div>
      </div>
      <div class="kpi-card">
        <div class="kpi-value">5.9%</div>
        <div class="kpi-label">CVaR 99%</div>
      </div>
    </div>
  </div>`;
}
