/**
 * MT5 Strategy Tester Runner
 * Spec: INI generation, process runner, report parsers
 */

import { v4 as uuidv4 } from 'uuid';
import type { TesterConfig, TesterRunResult, MT5Metrics, MT5Trade, WorkerDirectory } from '@/types/electron-api.d.ts';

// ============= INI Generation =============

interface INISection {
  [key: string]: string | number | boolean;
}

/**
 * Generate MT5 Strategy Tester INI file content
 */
export function generateTesterINI(config: TesterConfig, workerId: string): string {
  const lines: string[] = [
    '; Generated by MMC',
    `; Worker: ${workerId}`,
    `; Date: ${new Date().toISOString()}`,
    '',
    '[Tester]',
    `Expert=${config.expert}`,
    `ExpertParameters=${config.expertParameters}`,
    `Symbol=${config.symbol}`,
    `Period=${config.period}`,
    `FromDate=${config.fromDate}`,
    `ToDate=${config.toDate}`,
    `Deposit=${config.deposit}`,
    `Leverage=${config.leverage}`,
    `Model=${getModelCode(config.model)}`,
    `Optimization=${getOptimizationCode(config.optimization)}`,
    `Report=${config.reportPath}`,
    'ReplaceReport=1',
    'ShutdownTerminal=1',
    'Visual=0',
  ];

  return lines.join('\r\n');
}

function getModelCode(model: TesterConfig['model']): number {
  switch (model) {
    case 'EveryTick': return 0;
    case 'OHLC1Minute': return 1;
    case 'OpenPrices': return 2;
    case 'MathCalculations': return 3;
    default: return 0;
  }
}

function getOptimizationCode(optimization: TesterConfig['optimization']): number {
  switch (optimization) {
    case 'Disabled': return 0;
    case 'Complete': return 1;
    case 'Genetic': return 2;
    case 'AllSymbols': return 3;
    default: return 0;
  }
}

// ============= Report Parsing =============

/**
 * Parse MT5 HTML report into structured data
 */
export function parseHTMLReport(html: string): Partial<TesterRunResult> {
  const metrics = extractMetrics(html);
  const equity = extractEquityCurve(html);
  const drawdown = extractDrawdownCurve(html);
  const trades = extractTrades(html);

  return {
    success: true,
    metrics,
    equity,
    drawdown,
    trades,
  };
}

/**
 * Extract key metrics from HTML report
 */
function extractMetrics(html: string): MT5Metrics {
  const metrics: MT5Metrics = {
    netProfit: extractNumber(html, /Total Net Profit.*?<td[^>]*>([^<]+)/i) || 0,
    grossProfit: extractNumber(html, /Gross Profit.*?<td[^>]*>([^<]+)/i) || 0,
    grossLoss: Math.abs(extractNumber(html, /Gross Loss.*?<td[^>]*>([^<]+)/i) || 0),
    profitFactor: extractNumber(html, /Profit Factor.*?<td[^>]*>([^<]+)/i) || 0,
    recoveryFactor: extractNumber(html, /Recovery Factor.*?<td[^>]*>([^<]+)/i) || 0,
    sharpeRatio: extractNumber(html, /Sharpe Ratio.*?<td[^>]*>([^<]+)/i) || 0,
    maxDrawdown: Math.abs(extractNumber(html, /Maximal Drawdown.*?<td[^>]*>([^<]+)/i) || 0),
    maxDrawdownPct: extractNumber(html, /Maximal Drawdown.*?<td[^>]*>[^<]+\(([^%]+)/i) || 0,
    totalTrades: extractNumber(html, /Total Trades.*?<td[^>]*>([^<]+)/i) || 0,
    winningTrades: extractNumber(html, /Profit Trades.*?<td[^>]*>([^<]+)/i) || 0,
    losingTrades: extractNumber(html, /Loss Trades.*?<td[^>]*>([^<]+)/i) || 0,
    winRate: 0,
    avgWin: extractNumber(html, /Average Profit Trade.*?<td[^>]*>([^<]+)/i) || 0,
    avgLoss: Math.abs(extractNumber(html, /Average Loss Trade.*?<td[^>]*>([^<]+)/i) || 0),
    largestWin: extractNumber(html, /Largest Profit Trade.*?<td[^>]*>([^<]+)/i) || 0,
    largestLoss: Math.abs(extractNumber(html, /Largest Loss Trade.*?<td[^>]*>([^<]+)/i) || 0),
    avgHoldTime: 0,
    profitPerMonth: 0,
    expectedPayoff: extractNumber(html, /Expected Payoff.*?<td[^>]*>([^<]+)/i) || 0,
  };

  // Calculate win rate
  if (metrics.totalTrades > 0) {
    metrics.winRate = (metrics.winningTrades / metrics.totalTrades) * 100;
  }

  return metrics;
}

function extractNumber(html: string, pattern: RegExp): number | null {
  const match = html.match(pattern);
  if (match && match[1]) {
    const num = parseFloat(match[1].replace(/[^0-9.-]/g, ''));
    return isNaN(num) ? null : num;
  }
  return null;
}

/**
 * Extract equity curve data from HTML
 */
function extractEquityCurve(html: string): number[] {
  const equity: number[] = [];
  
  // Look for equity data in chart or table
  const equityMatch = html.match(/Balance.*?(\d[\d\s.,]+)/gi);
  if (equityMatch) {
    equityMatch.forEach(match => {
      const num = parseFloat(match.replace(/[^0-9.-]/g, ''));
      if (!isNaN(num)) {
        equity.push(num);
      }
    });
  }

  // If no equity data found, return empty - do NOT generate random data
  // Real data must come from actual trade extraction
  if (equity.length === 0) {
    // Return empty array - UI should show "Curve unavailable" message
    return [];
  }

  return equity;
}

/**
 * Extract drawdown curve from HTML
 */
function extractDrawdownCurve(html: string): number[] {
  const drawdown: number[] = [];
  const equity = extractEquityCurve(html);
  
  if (equity.length > 0) {
    let peak = equity[0];
    equity.forEach(value => {
      if (value > peak) peak = value;
      const dd = ((peak - value) / peak) * 100;
      drawdown.push(dd);
    });
  }

  return drawdown;
}

/**
 * Extract trades from HTML report - with proper timestamp parsing
 */
function extractTrades(html: string): MT5Trade[] {
  const trades: MT5Trade[] = [];
  
  // Match trade rows in HTML table
  const tradePattern = /<tr[^>]*>.*?<td[^>]*>(\d+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>(buy|sell)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<\/tr>/gi;
  
  // Also try to find close time column
  const closeTimePattern = /<tr[^>]*>.*?<td[^>]*>(\d+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>([^<]+)<\/td>.*?<td[^>]*>(buy|sell)<\/td>/gi;
  
  let match;
  while ((match = tradePattern.exec(html)) !== null) {
    const openTimeStr = match[2];
    const openTime = parseTradeTimestamp(openTimeStr);
    
    // Try to find close time from the row - if not found, set to null (not Date.now())
    // Close time should be parsed from the actual report data
    let closeTime: number | null = null;
    
    // Look for a close time pattern in this trade row
    const rowHtml = match[0];
    const closeMatch = rowHtml.match(/(\d{4}[.\/-]\d{2}[.\/-]\d{2}\s+\d{2}:\d{2}(?::\d{2})?)/g);
    if (closeMatch && closeMatch.length >= 2) {
      closeTime = parseTradeTimestamp(closeMatch[1]);
    }
    
    trades.push({
      ticket: parseInt(match[1], 10),
      openTime: openTime,
      closeTime: closeTime ?? openTime, // Use openTime as fallback, not Date.now()
      type: match[3].toLowerCase() as 'buy' | 'sell',
      lots: parseFloat(match[4]) || 0.01,
      symbol: match[5] || 'EURUSD',
      openPrice: parseFloat(match[6]) || 0,
      closePrice: parseFloat(match[7]) || 0,
      sl: parseFloat(match[8]) || 0,
      tp: parseFloat(match[9]) || 0,
      profit: parseFloat(match[10]) || 0,
      commission: 0,
      swap: 0,
      comment: '',
    });
  }

  return trades;
}

/**
 * Parse timestamp from MT5 report format
 * Handles formats like "2024.01.15 10:30:00" or "2024/01/15 10:30"
 */
function parseTradeTimestamp(timeStr: string): number {
  if (!timeStr || timeStr.trim() === '') {
    return 0; // Return 0 to indicate missing timestamp
  }
  
  // Normalize separators
  const normalized = timeStr
    .replace(/\./g, '-')
    .replace(/\//g, '-')
    .trim();
  
  const date = new Date(normalized);
  if (!isNaN(date.getTime())) {
    return date.getTime();
  }
  
  // Fallback: return 0 for unparseable timestamps
  return 0;
}

// ============= Worker Directory Management =============

const WORKER_BASE_DIR = '%APPDATA%/MMC/MT5Workers';

/**
 * Get worker directory configuration
 */
export function getWorkerConfig(workerId: string): WorkerDirectory {
  return {
    id: workerId,
    path: `${WORKER_BASE_DIR}/Worker-${workerId}`,
    status: 'idle',
  };
}

/**
 * Create worker directories for concurrent runs
 */
export function createWorkerDirectories(count: number): WorkerDirectory[] {
  const workers: WorkerDirectory[] = [];
  const letters = ['A', 'B', 'C', 'D'];
  
  for (let i = 0; i < Math.min(count, 4); i++) {
    workers.push({
      id: letters[i],
      path: `${WORKER_BASE_DIR}/Worker-${letters[i]}`,
      status: 'idle',
    });
  }
  
  return workers;
}

// ============= Run Management =============

/**
 * Create a unique run ID
 */
export function createRunId(eaName: string): string {
  const timestamp = Date.now();
  const short = uuidv4().split('-')[0];
  return `${eaName}_${timestamp}_${short}`;
}

/**
 * Get report file path for a run
 */
export function getReportPath(runId: string, workerId: string): string {
  return `${WORKER_BASE_DIR}/Worker-${workerId}/Reports/${runId}.html`;
}

// ============= Process Runner (Desktop Only) =============

/**
 * Run MT5 Strategy Tester (requires Electron)
 * This is a placeholder - actual implementation uses Electron IPC
 */
export async function runStrategyTester(
  config: TesterConfig,
  workerId: string,
  onProgress?: (progress: number) => void
): Promise<TesterRunResult> {
  const runId = createRunId(config.expert);
  const reportPath = getReportPath(runId, workerId);
  const startTime = Date.now();

  // Check if running in Electron
  if (!window.electronAPI) {
    return {
      success: false,
      runId,
      reportPath,
      error: 'Strategy Tester requires desktop mode',
      duration: 0,
    };
  }

  try {
    // Generate INI file
    const iniContent = generateTesterINI({ ...config, reportPath }, workerId);
    const iniPath = `${WORKER_BASE_DIR}/Worker-${workerId}/tester.ini`;
    
    // Write INI via Electron
    await window.electronAPI.writeFile(iniPath, iniContent);
    
    // Run tester via Electron
    const result = await window.electronAPI.runTester(iniPath, workerId, runId);
    
    return {
      ...result,
      runId,
      reportPath,
      duration: Date.now() - startTime,
    };
  } catch (error) {
    return {
      success: false,
      runId,
      reportPath,
      error: error instanceof Error ? error.message : 'Unknown error',
      duration: Date.now() - startTime,
    };
  }
}

/**
 * Parse a report file (requires Electron)
 */
export async function parseReportFile(reportPath: string): Promise<Partial<TesterRunResult>> {
  if (!window.electronAPI) {
    return { success: false, error: 'Requires desktop mode' };
  }

  try {
    const html = await window.electronAPI.readFile(reportPath);
    return parseHTMLReport(html);
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to parse report',
    };
  }
}
